package com.skywatch.event;

public enum EventType {
    ECLIPSE_SOLAR, ECLIPSE_LUNAR, METEOR_SHOWER, CONJUNCTION,
    OPPOSITION, TRANSIT, SUPERMOON, COMET,
    SOLAR_FLARE, CME, GEOMAGNETIC_STORM, AURORA, OCCULTATION,
    OTHER
}
